# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run:
          name: install app dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install deploy dependencies
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python test.py
      - run:
          name: cf login
          command: cf login -a https://api.fr.cloud.gov -u e1f20773-d686-48b8-a4a7-08c56abcbe3e -p $CF_PASS -o sandbox-va -s patrick.bateman

      - run:
          name: deploy via cf
          command: cf push
